### ISSUE TITLE
32:9 support improvements

### ISSUE THREAD

**Issue by Fl0riaS** [dvlden/uw-pub#17]
**Is your feature request related to a problem? Please describe.**
There is no good way to watch wide videos on 32:9 screen in f.e Disney plus. Modes in this addon works better than default, but they are not perfect. Stretch mode makes everything ultra wide and upscale mode cuts video on top and bottom part.

**Describe the solution you'd like**
For me ideal way to watch videos on 32:9 screen would be to fit video as much as its can be fitted, and left black bars on the left and right portion of the screen. 

**Describe alternatives you've considered**
I didn`t find any alternative

**Additional context**
Some visualization of current problem and solution that I would like
![32-9support](https://github.com/dvlden/uw-pub/assets/106116830/4c9c9691-9491-4eb9-abc0-82fd8c9b70a3)

**Comment by nnx0r** [comment]
Thank you for requesting this feature. I do plan to support it in the near future.
I believe you can currently rely on custom scaling X/Y, where you'd proportionally increment until you are satisfied.

Is it achievable that way? I do understand if it's annoying to do so, but sounds like a solution until improvement is implemented.

Please let me know!

**Comment by Fl0riaS** [comment]
Yes, after some fiddling I managed to get my desire behaviour using normal mode with scaling. It is achievable in this way, but without 2 monitors it is kinda annoying to do, because of constant need to enter fullscreen, look how video is behaving, leave fullscreen, adjust, repeat. Shortcut for changing scaling would definitely help, but I guess that it is not currently implemented on Firefox. Anyway, it is the best addon that I could find right now and thank you for your hard work. I`ll wait impatiently for native support or/and shortcuts for changing scaling :)

**Comment by nnx0r** [comment]
Thanks for your response!
I will keep this in mind. I can definitely add shortcuts for scaling, but I cannot suggest them, due to browser limits. 

When I add them, you'd need to go to keyboard shortcuts config from Firefox and fill-in the blank fields to whatever key combination you'd prefer. 

I will definitely add shortcuts, along with this Disney Plus fix #15 .
I'll plan to support it natively without mode+scaling requirement in the future release.

I understand the frustration. Firefox doesn't allow Popup toggle within fullscreen video, unlike Chromium. It'd make life much easier for Firefox users to have popup over the video for easy configuration. :)

**Comment by nnx0r** [comment]
I forgot to say that this was already requested on #14 (discussion).
I'll move it there, so you and I, among others can track the status from there.

Shortcuts are implemented: [Project Item](https://github.com/users/dvlden/projects/2?pane=issue&itemId=56088373)

Release is coming soon!
