### ISSUE TITLE
CTRL + mouse wheel zooms browser while switching modes

### ISSUE THREAD

**Issue by LeonNamowitz** [dvlden/uw-pub#3]
**Describe the bug**
Using the CTRL + mouse wheel bind to switch modes simultaneously changes the browser zoom for the current page. 
I tried this on Youtube, Twitch, Disney Plus, Netflix. Same behavior, so I imagine it's not site specific.
 

**To Reproduce**
1. Go to e.g. Youtube and watch a video in fullscreen.
2. Use the default CTRL + mouse wheel bind to change the mode.
3. Browser zoom increases.

**Expected behavior**
Browser zoom shouldn't be affected.

**Screenshots/Videos**
[Video](https://streamable.com/qzqrcz)

**Desktop (please complete the following information):**
 - OS: 
![2024-01-05 13_22_57-Window](https://github.com/dvlden/uw-pub/assets/104039044/c13c3271-4829-43e7-85a7-e64c47364b7b)

 - Browser: Chrome
 - Version 120.0.6099.200 (64-bit)

**Additional context**
Let me know if you need more information on this from me.
Also I do really like the mouse wheel idea so I would just suggest changing the bind to ALT + mouse wheel, which is pretty much the same, just hopefully with less conflicts.

**Comment by dvlden** [comment]
Thank you so much @LeonNamowitz for creating such a helpful issue.
I will look into this today and make a fix.

`Ctrl` is the magical key that is automatically being used for trackpads with multi-gestures. That's why pinch on trackpad works without holding any keys.

So I have to use that key for Mouse as well, because it's the same event. But I think I can prevent the default action of browser zooming. Not sure now that you described how it works, but I'll try.

**Comment by dvlden** [comment]
Just a quick update. I tried using mouse on macOS and it does not zoom, but on Windows it does, just like you described. 

I have just patched it, but I will not release it just yet. 
Doing some further testing on various platforms, just to make sure that it's consistent.

I block the browser zoom while video is in fullscreen and I restore it once you go out of fullscreen.

Keep you updated.

**Comment by LeonNamowitz** [comment]
> Ctrl is the magical key that is automatically being used for trackpads with multi-gestures. That's why pinch on trackpad works without holding any keys.

Wow that's really interesting, I didn't know that's how it worked.



> I have just patched it, but I will not release it just yet.

That's great to hear. You are really quick to respond and even fix it, thanks a lot. Sorry for being so mean earlier, I was just really frustrated.

**Comment by nnx0r** [comment]
No worries, I know the feeling.
Glad that you actually helped me out with such a wonderful report and you also updated your review. Not many people are built that way. 

I usually receive negative review and they never come back with further explanation or to even tell me if it works after the fix.

**EDIT:**
I just added it to "Done", but pending "Release"
[Project Board](https://github.com/users/dvlden/projects/2)

I cannot release it just yet, because many users did not update to new version yet. And at the moment, I am showing onboarding tutorial for first time installations and for every update. Which may annoy a lot of people and make them leave negative review or uninstall the extension.

Aside, Firefox store did not approve my update yet and it's taking them so long. So would be great if they approve v3.0.3 before I push this change.

Hope you do understand my problem here, but hoping once weekend pass, I can push it to the release.

**Comment by nnx0r** [comment]
This has been resolved in latest release and is now public. 
@LeonNamowitz can you confirm that you no longer have problems?

**Comment by LeonNamowitz** [comment]
Yup, everything works as intended now. Thanks again for the quick fix.
